name: 'Automatic build'
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
        runs-on: ubuntu-latest
        node-version: '16.x'

      - name: Deploy
        run: bash tools/deploy.sh
